### ISSUE TITLE
Disable wasm

### ISSUE THREAD

**Issue by dancixx** [ajrcarey/pdfium-render#180]
Hi there,

Is it possible to disable Wasm? The use case is that I don't need Wasm, actually, but using the macOS native build gives an error when I try to compile it. Another part of the project uses a higher version of wasm-bindgen, and there is a version mismatch. 

```
error: failed to select a version for `wasm-bindgen`.
    ... required by package `pdfium-render v0.8.27`
    ... which satisfies dependency `pdfium-render = "^0.8.27"` of package `engine v0.1.0 (/Users/danixx/Desktop/rag-rs/engine)`
    ... which satisfies path dependency `engine` (locked to 0.1.0) of package `server v0.1.0 (/Users/danixx/Desktop/rag-rs/server)`
versions that meet the requirements `<=0.2.95` are: 0.2.95, 0.2.93, 0.2.92, 0.2.91, 0.2.90, 0.2.89, 0.2.87, 0.2.86, 0.2.85, 0.2.84, 0.2.83, 0.2.82, 0.2.81, 0.2.80, 0.2.79, 0.2.78, 0.2.77, 0.2.76, 0.2.75, 0.2.74, 0.2.73, 0.2.72, 0.2.71, 0.2.70, 0.2.69, 0.2.68, 0.2.67, 0.2.66, 0.2.65, 0.2.64, 0.2.63, 0.2.62, 0.2.61, 0.2.60, 0.2.59, 0.2.58, 0.2.57, 0.2.56, 0.2.55, 0.2.54, 0.2.53, 0.2.52, 0.2.51, 0.2.50, 0.2.49, 0.2.48, 0.2.47, 0.2.46, 0.2.45, 0.2.44, 0.2.43, 0.2.42, 0.2.41, 0.2.40, 0.2.39, 0.2.38, 0.2.37, 0.2.36, 0.2.35, 0.2.34, 0.2.33, 0.2.32, 0.2.31, 0.2.30, 0.2.29, 0.2.28, 0.2.27, 0.2.26, 0.2.25, 0.2.24, 0.2.23, 0.2.22, 0.2.21, 0.2.20, 0.2.19, 0.2.18, 0.2.17, 0.2.16, 0.2.15, 0.2.14, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.0

the package `pdfium-render` depends on `wasm-bindgen`, with features: `enable-interning` but `wasm-bindgen` does not have these features.


all possible versions conflict with previously selected packages.

  previously selected package `wasm-bindgen v0.2.97`
    ... which satisfies dependency `wasm-bindgen = "=0.2.97"` of package `dashboard v0.1.0
```

**Comment by ajrcarey** [comment]
Hi @dancixx , thank you for reporting the issue. As you can see from https://github.com/ajrcarey/pdfium-render/blob/master/Cargo.toml#L43, compilation to WASM is only used when the compilation target for your project is `wasm32`. I have no difficulty here in building `pdfium-render` on a Mac using the native target; at no point are any WASM-related dependencies introduced.

Please post the exact commands and `Cargo.toml` necessary to reproduce the problem.

**Comment by ajrcarey** [comment]
> dependency `wasm-bindgen = "=0.2.97"` of package `dashboard v0.1.0`

This strongly suggests to me you have a WASM dependency in your own project. Why do you have that dependency if, as you say, you "don't need Wasm"?

**Comment by dancixx** [comment]
@ajrcarey I have a workspace, where I also have a leptos project for the frontend, where I need to use wasm. But actually, I do not really understand why the wasm32 target is active, I am trying to build it on macos or linux in docker later. I tried a lot of settings, but for some reason cargo sees wasm32 in some way?!

My `Cargo.toml` where this crate is used
```toml
[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
async-stream = "0.3.6"
common = { path = "../common" }
dotenvy = "0.15.7"
either = "1.13.0"
fastembed = "4.2.0"
futures = "0.3.31"
indexmap = "2.6.0"
lopdf = { version = "0.34.0", features = ["pom", "pom_parser"] }
mistralrs = { git = "https://github.com/EricLBuehler/mistral.rs.git" }
pdfium-render = "0.8.27"
qdrant-client = { version = "1", features = ["serde"] }
rayon = { version = "1.10.0", optional = true }
serde = "1.0.215"
serde_json = "1.0.133"
tokio = "1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-test = "0.2.5"
uuid = { version = "1.11.0", features = ["v4"] }

[dev-dependencies]
tempfile = "3"

[features]
default = ["model"]
rayon = ["dep:rayon"]
cuda = ["mistralrs/cuda", "mistralrs/flash-attn", "mistralrs/cudnn"]
metal = ["mistralrs/metal"]
model = []

[lib]
path = "src/lib.rs"
```

My frontend `Cargo.toml`:
```toml
[package]
name = "dashboard"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.7.0", features = ["nightly"] }
leptos_router = { version = "0.7.0", features = ["nightly"] }
axum = { version = "0.7", optional = true }
common = { path = "../common" }
console_error_panic_hook = "0.1"
leptos_axum = { version = "0.7.0", optional = true }
leptos_meta = { version = "0.7.0" }
tokio = { version = "1", features = ["rt-multi-thread"], optional = true }
tower = { version = "0.5.1", optional = true }
tower-http = { version = "0.6.2", features = ["fs"], optional = true }
wasm-bindgen = "=0.2.97"
thiserror = "1"
tracing = { version = "0.1", optional = true }
http = "1"
reqwest = { version = "0.12.9", features = ["stream", "json"] }
serde = "1.0.215"
futures = "0.3.31"
serde_json = "1.0.133"
leptos-use = "0.15.0"

[features]
hydrate = ["leptos/hydrate"]
ssr = [
    "dep:axum",
    "dep:tokio",
    "dep:tower",
    "dep:tower-http",
    "dep:leptos_axum",
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:tracing",
    "leptos-use/ssr",
]

# Defines a size-optimized profile for the WASM bundle in release mode
[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle. Defaults to the crate name
output-name = "dashboard"

# The site root folder is where cargo-leptos generate all output. WARNING: all content of this folder will be erased on a rebuild. Use it in your server setup.
site-root = "target/site"

# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
# Defaults to pkg
site-pkg-dir = "pkg"

# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS. The CSS is optimized by Lightning CSS before being written to <site-root>/<site-pkg>/app.css
style-file = "style/output.css"
tailwind-input-file = "style/input.css"
tailwind-config-file = "tailwind.config.js"

# Assets source dir. All files found here will be copied and synchronized to site-root.
# The assets-dir cannot have a sub directory with the same name/path as site-pkg-dir.
#
# Optional. Env: LEPTOS_ASSETS_DIR.
assets-dir = "public"

# The IP and port (ex: 127.0.0.1:3000) where the server serves the content. Use it in your server setup.
site-addr = "127.0.0.1:3000"

# The port to use for automatic reload monitoring
reload-port = 3001

# [Optional] Command to use when running end2end tests. It will run in the end2end dir.
#   [Windows] for non-WSL use "npx.cmd playwright test"
#   This binary name can be checked in Powershell with Get-Command npx
# end2end-cmd = "npx playwright test"
# end2end-dir = "end2end"

#  The browserlist query used for optimizing the CSS.
browserquery = "defaults"

# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"

# The features to use when compiling the bin target
#
# Optional. Can be over-ridden with the command line parameter --bin-features
bin-features = ["ssr"]

# If the --no-default-features flag should be used when compiling the bin target
#
# Optional. Defaults to false.
bin-default-features = false

# The features to use when compiling the lib target
#
# Optional. Can be over-ridden with the command line parameter --lib-features
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
#
# Optional. Defaults to false.
lib-default-features = false

# The profile to use for the lib target when compiling for release
#
# Optional. Defaults to "release".
lib-profile-release = "wasm-release"

```

and my workspace toml file:
```toml
[workspace]
resolver = "2"
members = ["common", "dashboard", "engine", "server"]

[workspace.dependencies]

```
